#!/bin/sh
#获取IP
ip=`curl -s 'http://checkip.dyndns.org' | sed 's/.*Current IP Address: \([0-    9\.]*\).*/\1/g'`
echo "Sending ip $ip..."
#发送邮件
to="os.sec@qq.com"
subject="IP"
message="IP is $ip"
headers="server@serverdomain.com"
echo $message | mail -s $subject $to -- -f $headers
echo "Send OK!"
 
