all:
	g++ usaco.cpp  -o ../bin/usaco
	g++ newacm.cpp -o ../bin/newacm
	g++ flash.cpp  -o ../bin/flash
	g++ testnew.cpp -o ../bin/testnew

newacm:
	g++ newacm.cpp -o ../bin/newacm

usaco:
	g++ usaco.cpp  -o ../bin/usaco

flash:
	g++ flash.cpp  -o ../bin/flash

test:
	g++ testnew.cpp -o ../bin/testnew


